version: "2"

services:
  postgres:
    image: postgres:latest
    container_name: finance-ai-database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRESS_DB: finance-ai
    ports:
      - "5432:5432"
    volumes:
      - ./.postgres-data:/var/lib/postgressql/data

volumes:
  .postgres-data:
